name: vocabulary_app
description: 이미지에서 영어 단어와 예문을 자동으로 추출하는 앱
publish_to: 'none'
version: 1.0.4+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.5+3  # 이미지 선택/촬영ㄱ
  http: ^1.3.0  # OpenAI API 호출에 필요
  path_provider: ^2.0.11 # 파일 시스템 경로
  flutter_tts: ^3.8.5   # 텍스트 음성 변환 (최신 버전으로 업데이트)
  google_fonts: ^6.2.0  # 구글 폰트 사용 (모던 UI 위한 폰트)
  sqflite: ^2.4.2
  path: ^1.8.3     # 파일 경로 관리
  shared_preferences: ^2.5.3
  provider: ^6.1.4
  flutter_secure_storage: ^4.2.1
  in_app_purchase: ^3.2.1
  firebase_core: ^3.13.0
  firebase_remote_config: ^5.4.3
  google_mobile_ads: ^5.3.1
  app_tracking_transparency: ^2.0.6+1
  flutter_staggered_animations: ^1.1.1
  table_calendar: ^3.2.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.2.0
  flutter_native_splash: ^2.3.10  # 최신 버전을 사용하세요

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/images/guide/
  
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.ttf
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700

flutter_native_splash:
  color: "#FFFFFF"  # 배경색 (흰색)
  image: assets/splash.png  # 스플래시 이미지 경로
  # 또는 색상 배경에 텍스트 표시
  color_dark: "#121212"  # 다크모드 배경색
  image_dark: assets/splash.png  # 다크모드 이미지
  android_12:
    image: assets/splash.png  # Android 12 이상용 이미지
    icon_background_color: "#FFFFFF"
  fullscreen: true
  android: true
  ios: true