name: vocabulary_app
description: 이미지에서 영어 단어와 예문을 자동으로 추출하는 앱
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.5+3  # 이미지 선택/촬영
  # google_ml_kit 제거 (OpenAI API를 사용하므로 불필요)
  http: ^1.3.0  # OpenAI API 호출에 필요
  path_provider: ^2.0.11 # 파일 시스템 경로
  share_plus: ^4.0.10   # 공유 기능
  flutter_tts: ^3.8.5   # 텍스트 음성 변환 (최신 버전으로 업데이트)
  google_fonts: ^6.2.0  # 구글 폰트 사용 (모던 UI 위한 폰트)
  sqflite: ^2.4.2
  path: ^1.8.3     # 파일 경로 관리
  shared_preferences: ^2.5.3
  provider: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.2.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/images/guide/
  
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.ttf
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700